name: Format Check
on:
  pull_request:
    # filter on files that should trigger this workflow
    paths:
      - 'pyproject.toml'
      - '**.py'
      - '.github/workflows/black.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  black:
    name: Format Check with Black
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v3

      - name: Check format of TrueLearn
        uses: psf/black@stable
        with:
          options: "--check"
          src: "./truelearn"
