name: Format Check
on: [pull_request]

jobs:
  run:
    name: Format Check with Black
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@v3

    - name: Check format of TrueLearn
    - uses: psf/black@stable
      with:
        options: "--check"
        src: "./truelearn"
