name: Code Coverage
on:
  push:
    branches:
      - main
      - setup-ci
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  Code_Coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          persist-credentials: false
          # otherwise, you will failed to push refs to dest repo
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4.4.0
        with:
          python-version: '3.10'

      - name: Install Project Dependencies
        run: python setup.py install

      - name: Install Pytest
        run: pip install pytest

      #Note PyCov is an extended form of coverage.py
      - name: Install Pytest-cov
        run: pip install pytest-cov


      - name: Calculate coverage
        #Inc. branch + statement coverage
        run: |
          pytest --cov-branch --cov-report "xml:coverage.xml" --cov=truelearn_experiments unit_tests
      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-xml-coverage-path: ./coverage.xml
          hide-report: true

      - name: Update Readme with Coverage Html
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          sed -i '/<!-- Pytest Coverage Comment:Begin -->/,/<!-- Pytest Coverage Comment:End -->/c\<!-- Pytest Coverage Comment:Begin -->\n\${{ steps.summary_report.outputs.content }}\n<!-- Pytest Coverage Comment:End -->' ./README.md
      - name: Commit & Push changes to Readme
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions-js/push@master
        with:
          message: Update coverage on Readme
          github_token: ${{ secrets.GITHUB_TOKEN }}
      

