# Ensures that the docs build correctly
name: "Docs Build"
on:
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs:
    sphinx_build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v3

            - name: Setup Python
              uses: actions/setup-python@v4.4.0
              with:
                  python-version: "3.7"
                  cache: "pip" # Cache dependencies
                  cache-dependency-path: "**/pyproject.toml"

            - name: Install pip-tools and generate requirements.txt
              run: |
                  pip install pip-tools
                  # Generates a requirements.txt file from pyproject.toml
                  # This means that we dont have to install truelearn
                  # so this workflow can use the same cache as the other workflows
                  pip-compile --resolver=backtracking --output-file requirements.txt pyproject.toml

            - name: Install Project Dependencies
              run: pip install -r requirements.txt

            - name: Install Doc Dependencies
              run: |
                  pip install .[docs]

            - name: Sphinx Problem Matcher
              uses: ammaraskar/sphinx-problem-matcher@master

            - name: Sphinx direct build
              run: |
                  sphinx-apidoc -f -o docs/ truelearn
                  cd ./docs

                  # Treat warnings as errors by setting the SPHINXOPTS variable to -W.
                  # --keep-going is for not stopping at the first error
                  # -n is for nitpicky mode warns about all missing references
                  make html -e SPHINXOPTS="-W --keep-going -n"
