name: 'Docs: Build and Deploy'
on:
  push:
    branches:
      #For debugging only
      - documentation-generation
  release:
    types:
      - published
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  Sphinx_Build:
    uses: ./.github/workflows/docs_build.yml

# Deployment to GitHub Pages
# See: https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#choosing-a-publishing-source
  Deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: Sphinx_Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      #Debugging
      - run: ls
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload Sphinx Build
          path: './docs/_build/html/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1