name: 'Docs: Build and Deploy'
on:
  push:
    branches:
      #For debugging only
      - documentation-generation
  release:
    types:
      - published
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  Sphinx_Build:
    uses: ./.github/workflows/docs_build.yml
    with:
      branch: ${{ github.ref }}

# Build the Jekyll site
  Jekyll_Build:
    runs-on: ubuntu-latest
    needs: Sphinx_Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./docs/_build/html
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1

# Deployment to GitHub Pages
  Deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: Jekyll_Build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1


