name: Static analysis
on:
  push:
    branches:
      - main
      - setup-ci
  pull_request:
    branches:
      - main
  workflow_dispatch:


jobs:
  Run_Prospector_Analysis:
    runs-on: ubuntu-latest
    env: 
      RESULTS_PATH: ./
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Prospector
        run: pip install prospector

      - name: Run Prospector
        run: |
          #Outputs the xunit xml to project root
          prospector --output-format xunit:prospector_report.xml
      - name: Generate Report
        uses: AutoModality/action-xunit-viewer@v1.0.1
        with:
          results: ${{ env.RESULTS_PATH }}

      - name: Attach report
        if: success() || failure()
        uses: actions/upload-artifact@v1
        with:
          name: "Prospector Analysis Report"
          path: ${{ env.RESULTS_PATH }}
          

