name: Static analysis
on:
  push:
    branches:
      - main
      - setup-ci
  pull_request:
    branches:
      - main
  workflow_dispatch:


jobs:
  Run_Prospector_Analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4.4.0
        with:
          python-version: '3.10'

      - name: Install Project Dependencies
        run: python setup.py install

      - name: Install Prospector
        run: pip install prospector


      - name: Run Prospector
        run: |
          #Outputs the xunit report to project root
          prospector --full-pep8 --output-format xunit:prospector_report.xml

      #- name: Test Reporter
       # uses: phoenix-actions/test-reporting@v10

        #if: success()||failure()
        #with:
         # path: 'prospector_report.xml'
         # reporter: jest-junit
        #  name: 'Prospector Analysis Report'
      #- name: Publish report
      #  if: success() || failure()
      #  uses: jwgmeligmeyling/pmd-github-action@v1.2
      #  with:
      #    path: ./prospector_report.xml
      #    name: 'Static Analysis Report'
      #    title: 'Static Analysis Report'
      - name: Setup Dotnet
        uses: actions/setup-dotnet@v3
        
      - name: Convert xunit to Junit
        run: |
          dotnet tool install -g dotnet-xunit-to-junit
          dotnet xunit-to-junit "./prospector_report.xml" "prospector_junit.xml"


      - name: Convert test results to Github Annotations
        uses: mikepenz/action-junit-report@v3
        #Use success()||failure() to allow for manual cancellation of an action (see docs)
        if: success()||failure()
        with:
          #Report in project root
          report_paths: ./prospector_junit.xml
          check_name: "Prospector Analysis Report"
     # - name: Convert test results to Github Annotations
       # uses: EnricoMi/publish-unit-test-result-action@v2
        #Use success()||failure() to allow for manual cancellation of an action (see docs)
       # if: success()||failure()
       # with:
          #Report in project root
         # xunit_files: "prospector_report.xml"
          #junit_files: "prospector_report.xml"
        #  check_name: "Prospector Analysis Report"

          

name: Static analysis
on:
  push:
    branches:
      - main
      - setup-ci
  pull_request:
    branches:
      - main
  workflow_dispatch:


jobs:
  Run_Prospector_Analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4.4.0
        with:
          python-version: '3.10'

      - name: Install Project Dependencies
        run: python setup.py install

      - name: Install Prospector
        run: pip install prospector


      - name: Run Prospector
        run: |
          #Outputs the xunit report to project root
          prospector --full-pep8 --output-format xunit:prospector_report.xml

      #- name: Test Reporter
       # uses: phoenix-actions/test-reporting@v10

        #if: success()||failure()
        #with:
         # path: 'prospector_report.xml'
         # reporter: jest-junit
        #  name: 'Prospector Analysis Report'
      #- name: Publish report
      #  if: success() || failure()
      #  uses: jwgmeligmeyling/pmd-github-action@v1.2
      #  with:
      #    path: ./prospector_report.xml
      #    name: 'Static Analysis Report'
      #    title: 'Static Analysis Report'
      - name: Any Report to GitHub Annotations
        uses: JBZoo/CI-Report-Converter@master
        if: success()||failure()
        with:
          input-format: junit
          input-file: prospector_report.xml
          suite-name: Prospector Analysis Report

     # - name: Convert test results to Github Annotations
       # uses: EnricoMi/publish-unit-test-result-action@v2
        #Use success()||failure() to allow for manual cancellation of an action (see docs)
       # if: success()||failure()
       # with:
          #Report in project root
         # xunit_files: "prospector_report.xml"
          #junit_files: "prospector_report.xml"
        #  check_name: "Prospector Analysis Report"

          

