name: Spell Check
on: [pull_request, workflow_dispatch, workflow_call]

# Only cancel concurrent runs of the same workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-typo
  cancel-in-progress: true

jobs:
  typos:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v3.5.2

      - name: Check spelling of TrueLearn
        uses: crate-ci/typos@master
        with:
          files: ./truelearn ./docs
